# @package _global_

# Hyperparameters and ResNet18 from on https://arxiv.org/abs/2012.0611

defaults:
  - /benchmark/nav/pointnav: pointnav_pretrained_orbslam
  - /habitat_baselines: habitat_baselines_rl_config_base
  - _self_

habitat:
  env_task: LocNavEnv
  environment:
    max_episode_steps: 5000
  task:
    reward_measure: "distance_to_goal_reward"
    success_reward: 10.0
    slack_reward: 0.0
    measurements:
      orbslam_localization_reward:
        localization_reward_weight: 0.0
      orbslam_loop_closure_reward:
        loop_closure_reward_weight: 0.0
      early_stopping_penalty:
        penalty: 0.0
        prevent_termination: False

habitat_baselines:
  verbose: True
  trainer_name: "ddppo"
  tensorboard_dir: "/mnt/tb/orbslam-finetuned"
  video_dir: "/mnt/video_dir/orbslam-finetuned"
  test_episode_count: -1
  eval_ckpt_path_dir: "/mnt/model-weights/orbslam-finetuned.pth"
  num_environments: 8
  checkpoint_folder: "/mnt/checkpoints/orbslam-finetuned"
  total_num_steps: 10e6
  num_updates: -1
  log_interval: 1
  num_checkpoints: 100
  force_torch_single_threaded: True
  load_resume_state_config: False

  eval:
    video_option: ["disk"]

  rl:
    preemption:
      save_resume_state_interval: 1
    ppo:
      clip_param: 0.2
      ppo_epoch: 2
      num_mini_batch: 2
      value_loss_coef: 0.5
      entropy_coef: 0.1
      lr: 2.5e-4
      eps: 1e-5
      max_grad_norm: 0.2
      num_steps: 128
      use_gae: True
      gamma: 0.99
      tau: 0.95
      use_linear_clip_decay: False
      use_linear_lr_decay: False
      reward_window_size: 50
      use_normalized_advantage: False
      hidden_size: 512
      use_double_buffered_sampler: True

    ddppo:
      sync_frac: 0.6
      distrib_backend: GLOO
      pretrained_weights: /mnt/model-weights/gibson-4plus-resnet50.pth
      pretrained: False
      pretrained_encoder: True
      train_encoder: False
      reset_critic: True

      backbone: resnet50
      rnn_type: LSTM
      num_recurrent_layers: 2
