defaults:
  - task_config_base
  - actions:
    - velocity_control
  - measurements:
    - distance_to_goal
    - success
    - spl
    - soft_spl
    - soft_success
    - collisions
    - distance_to_goal_reward
    - orbslam_state
    - orbslam_position_error
    - orbslam_rotation_error
    - orbslam_pose_error
    - orbslam_localization_reward
    - orbslam_loop_closure_reward
    - early_stopping_penalty
    - localization_aware_distance_to_goal_reward
    - orbslam_top_down_map
  - lab_sensors:
    - pointgoal_with_gps_compass_sensor
    - orbslam_pointgoal_with_gps_compass_sensor_transformed
  - _self_

type: Nav-v0
end_on_success: True
reward_measure: "distance_to_goal_reward"
success_measure: "success"
goal_sensor_uuid: pointgoal_with_gps_compass
actions:
  velocity_control:
    time_step: 0.1
    lin_vel_range: [0.0, 0.25]
    ang_vel_range: [-30, 30]
