defaults:
  - task_config_base
  - actions:
    - velocity_control
  - measurements:
    - distance_to_goal
    - success
    - spl
    - soft_spl
    - soft_success
    - collisions
    - distance_to_goal_reward
    - top_down_map
  - lab_sensors:
    - pointgoal_with_gps_compass_sensor
    - pointgoal_with_gps_compass_sensor_transformed
  - _self_

type: Nav-v0
end_on_success: True
reward_measure: "distance_to_goal_reward"
success_measure: "success"
goal_sensor_uuid: pointgoal_with_gps_compass_transformed
actions:
  velocity_control:
    time_step: 0.1
    lin_vel_range: [0.0, 0.25]
    ang_vel_range: [-30, 30]
